language: go

go:
- 1.11.x
- master

env:
- GO111MODULE=on

before_install:
- go get -v

script:
- go test ./... -count=1 -coverprofile=coverage.txt -covermode=atomic -v

after_success:
- bash <(curl -s https://codecov.io/bash)
