spiders:
  kuaidaili:
    base: 'https://www.kuaidaili.com/free'
    types: ['inha', 'intr']
    page:
      from: 1
      to: 21
  ip3366:
    base: 'http://www.ip3366.net/free'
    types: ['1', '2']
    page:
      from: 1
      to: 8
  kaixin:
    base: 'http://www.kxdaili.com/dailiip'
    types: [ '1', '2' ]
    page:
      from: 1
      to: 11
  89ip:
    base: 'https://api.89ip.cn/tqdl.html?api=1'
    api:
      num: 500
