- name: 西刺代理
  enable: true
  urls:
    - https://www.xicidaili.com/{nn, nt}/{1...10}
  parser:
    query: //*[@id="ip_list"]/tbody/tr[@class="odd" or ""]
    ip: td[1]
    port: td[2]
- name: 快代理
  enable: true
  urls:
    - https://www.kuaidaili.com/ops/proxylist/{range(1, 10)}
    - https://www.kuaidaili.com/free/{intr, inha}/{range(1, 10)}
  parser:
    query: //*[@id="list" or "freelist"]/table/tbody/tr
    ip: td[@data-title='IP']
    port: td[@data-title='PORT']
